create table orders(
   orderId integer generated by default as identity (start with 1000) not null,
   orderDate timestamp not null,
   customer varchar not null,
   
   constraint pk_orders primary key (orderId),
   constraint fk_orders_customers foreign key (customer)
            references customers(username)
);

create table orderitems (
   orderId integer not null,
   productId varchar(255) not null,
   quantity double not null,
   constraint pk_orderitems primary key (orderId, productId),
   constraint fk_orderitems_orders foreign key (orderId) references orders(orderId),
   constraint fk_orderitems_products foreign key (productId) references products(productId)
);